title:  Objectarys
description: Programming, Logic and Other IT Concepts
show_downloads: false
google_analytics: UA-129903287-1
theme: jekyll-theme-minimal

disqus:
    shortname: www-objectary-com

linenos: true
