title:  Objectary
description: collecting topics from science and technology
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

disqus:
    shortname: www-objectary-com

linenos: true
